# Generated by Django 3.0.4 on 2020-04-16 12:57

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listening', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentence',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
